app = "koffan"
primary_region = "waw"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  DB_PATH = "/data/shopping.db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "koffan_data"
  destination = "/data"
